### ISSUE TITLE
not working when composing in HTML mode

### ISSUE THREAD

**Issue by crysman** [corbosman/keyboard_shortcuts#16]
CTRL+ENTER to send e-mail does not work when composing in HTML mode. Any fix possible?

**Comment by corbosman** [comment]
Works for me. What OS and browser?

**Comment by crysman** [comment]
Various. I've tested it twice:
1) Xubuntu 15.04 on a) Firefox b) Chromium (very recent versions)
2) MS Win 7 Pro on Firefox (very recent version)
In plain text it works.

**Comment by crysman** [comment]
debug1: "about" states: "keyboard_shortcuts	2.0.2", my collegue says he had to pull latest version in order to make it work on the mailserver (but again, only plaintext).

debug2: running "Roundcube Webmail 0.9.5"

**Comment by corbosman** [comment]
The latest version is 2.4.1

Also, you might want to upgrade to roundcube 1.1 as 0.9.5 is really old.

**Comment by kepi** [comment]
Hey, where is this 2.4.1 version? :) I'm maybe looking into bad place, but in this repository, there is only 2.0.2 according to package.xml

As for older version - its most up to date packaged version in Debian Wheezy, we don't want to update to upstream until absolutely necessary.

Thanks

**Comment by kepi** [comment]
Ah, I see it now in releases files. We used most recent version - 2.4.1 - it is probably not updated in package.xml. Just tested it but it is same version as on master.

**Comment by crysman** [comment]
So what is the resume, please? Do we have to update Roundcube in order to make it work, or there is something wrong with the xml package and versions?

**Comment by corbosman** [comment]
It's not possible. The HTML editor loads its own iframe, and it doesnt load any plugin code. So within the HTML editor no roundcube plugins exist. Therefore the keyboard shortcuts also dont work there.
